# Generated by Django 2.2.7 on 2019-12-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Torrent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300)),
                ('content', models.FileField(blank=True, upload_to='torrents/torrents')),
                ('miniature', models.URLField()),
                ('magnets', models.URLField()),
                ('release', models.IntegerField(blank=True)),
                ('category', models.CharField(blank=True, max_length=300)),
                ('rate', models.FloatField(blank=True)),
                ('synopsis', models.TextField(blank=True)),
                ('director', models.CharField(blank=True, max_length=300)),
                ('actors', models.TextField(blank=True)),
                ('movie_length', models.CharField(blank=True, max_length=300)),
                ('language', models.CharField(blank=True, max_length=300)),
                ('dlPath', models.CharField(blank=True, max_length=300)),
                ('comments', models.TextField(blank=True)),
                ('serie', models.BooleanField()),
                ('episodes', models.TextField(blank=True)),
                ('seasons', models.CharField(blank=True, max_length=4)),
                ('idimdb', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
