# Generated by Django 2.2.7 on 2019-12-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrent',
            name='watch_date',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
